### ISSUE TITLE
How to refresh the autocomplete data?

### ISSUE THREAD

**Issue by anantc88** [gch1p/bootstrap-5-autocomplete#23]
Hi,
Is there a way to refresh the autocomplete options once the list is loaded. For example, I am using a dropdown next to the search bar. Based on the selection in the dropdown, the results in the autocomplete should get filtered. 
However, if I fire the Autocomplete event every time a value is selected, it creates a new dropdown list based on the different datasource.
Any suggestions to refresh or destroy the existing autocomplete dropdown to repopulate with freshdata?

**Comment by Binternet** [comment]
@anantc88 see if this helps:
https://github.com/gch1p/bootstrap-5-autocomplete/issues/15

**Comment by lekoala** [comment]
if that can help someone, i created this
https://github.com/lekoala/bootstrap5-autocomplete
this has more features regarding server stuff
