### ISSUE TITLE
Autocomplete & Ajax

### ISSUE THREAD

**Issue by dugi07** [gch1p/bootstrap-5-autocomplete#5]
Is there any better option to use JSON to recive data from other file ?

`const` ac = new Autocomplete(field, {
`onInput:` function () {
`dane=AJAX();
`ac.setData(dane);  
` },
`data:` [{label: "Text formatu JSON", value: 42}],
.....
`

**Comment by sp00n** [comment]
I'm using the `onkeyup` event handler of the input field itself to set the data. But I'm not actually sure this is better than the `onInput` option, I've seen this only just now.

```js
document.getElementById("myInputField").addEventListener("keyup", function(event) {
    const val = this.value;

    // Get the data from AJAX, IndexedDb, whatever
    getDataFromWhereEver(val).then(function(entries) {
        ac.setData(entries);
    });
});
```

**Comment by dugi07** [comment]
Thx for answer.

**Comment by AgentSmith0** [comment]
Maybe an example could be added in the README file?
