### ISSUE TITLE
This does not work with accented characters such as ú

### ISSUE THREAD

**Issue by simon-stewart** [gch1p/bootstrap-5-autocomplete#8]
To get it to work for searchs with accented characters and accented items, you can add:

const removeDiacritics = function(str) {
    return str
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
}

and apply this in lines doing searches using indexOf such as

const idx = removeDiacritics(item.label).toLowerCase().indexOf(removeDiacritics(lookup).toLowerCase());

and 

if (removeDiacritics(item.label).toLowerCase().indexOf(removeDiacritics(lookup).toLowerCase()) >= 0) {
                items.appendChild(this.createItem(lookup, item));
                if (this.options.maximumItems > 0 && ++count >= this.options.maximumItems)
                    break;
            }

**Comment by gch1p** [comment]
Thank you!
